permalink: /:categories/:title
pygments: true
layout: default
paginate: 5
lsi: true

author: Kaleb Hornsby
description: Software Engineer in Augusta, GA.
keywords:
- Hypertext
- ECMAScript 5

title: Kaleb Hornsby
url: http://git.kaleb.hornsby.ws/

edit: https://github.com/kaleb/kaleb.github.com/file-edit/master