permalink: /:categories/:title
pygments: true
layout: default
paginate: true
lsi: true
exclude: []
maruku:
    use_tex: true

author: Kaleb Hornsby
email: kaleb@hornsby.ws
description: Software Engineer in Augusta, GA.
keywords:
- Hypertext
- ECMAScript 5

title: Kaleb Hornsby
url: http://git.kaleb.hornsby.ws

edit: https://github.com/kaleb/kaleb.github.com/file-edit/master