permalink: pretty
pygments: true
layout: default

author: Kaleb Hornsby
description: Software Engineer in Augusta, GA.
keywords:
- Hypertext
- ECMAScript 5

title: Kaleb Hornsby

edit: https://github.com/kaleb/kaleb.github.com/file-edit/master